services:

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: news
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
