spring:
  application:
      name: TestTaskNews

  profiles:
    active: prod

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true
    locations: classpath:db/migration

jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 30m



